import copy

characters = [
    "Shadow",
    "Gun Android",
    "Cannon Android"
]

# Every level and respective missions
levels = {
    "Westopolis"      :  ["Dark", "Normal", "Hero", "Expert"],
    "Digital Circuit" :  ["Dark", "Hero", "Expert"],
    "Glyphic Canyon"  :  ["Dark", "Normal", "Hero", "Expert"],
    "Lethal Highway"  :  ["Dark", "Hero", "Expert"],
    "Cryptic Castle"  :  ["Dark", "Normal", "Hero", "Expert"],
    "Prison Island"   :  ["Dark", "Normal", "Hero", "Expert"],
    "Circus Park"     :  ["Dark", "Normal", "Hero", "Expert"],
    "Central City"    :  ["Dark", "Hero", "Expert"],
    "The Doom"        :  ["Dark", "Normal", "Hero", "Expert"],
    "Sky Troops"      :  ["Dark", "Normal", "Hero", "Expert"],
    "Mad Matrix"      :  ["Dark", "Normal", "Hero", "Expert"],
    "Death Ruins"     :  ["Dark", "Hero", "Expert"],
    "The ARK"         :  ["Dark", "Normal", "Expert"],
    "Air Fleet"       :  ["Dark", "Normal", "Hero", "Expert"],
    "Iron Jungle"     :  ["Dark", "Normal", "Hero", "Expert"],
    "Space Gadget"    :  ["Dark", "Normal", "Hero", "Expert"],
    "Lost Impact"     :  ["Normal", "Hero", "Expert"],
    "GUN Fortress"    :  ["Dark", "Hero", "Expert"],
    "Black Comet"     :  ["Dark", "Hero", "Expert"],
    "Lava Shelter"    :  ["Dark", "Hero", "Expert"],
    "Cosmic Fall"     :  ["Dark", "Hero", "Expert"],
    "Final Haunt"     :  ["Dark", "Hero", "Expert"],
    "The Last Way"    :  ["Normal", "Expert"]
}

# Every boss in normal and expert
bosses = {
    "Black Bull (Lethal Highway)"  :  ["Normal", "Expert"],
    "Egg Breaker (Cryptic Castle)" :  ["Normal", "Expert"],
    "Heavy Dog"                    :  ["Normal", "Expert"],
    "Egg Breaker (Mad Matrix)"     :  ["Normal", "Expert"],
    "Black Bull (Death Ruins)"     :  ["Normal", "Expert"],
    "Blue Falcon"                  :  ["Normal", "Expert"],
    "Egg Breaker (Iron Jungle)"    :  ["Normal", "Expert"],
    "Diablon (GUN Fortress)"       :  ["Normal", "Expert"],
    "Black Doom (GUN Fortress)"    :  ["Normal", "Expert"],
    "Diablon (Black Comet)"        :  ["Normal", "Expert"],
    "Egg Dealer (Black Comet)"     :  ["Normal", "Expert"],
    "Egg Dealer (Lava Shelter)"    :  ["Normal", "Expert"],
    "Egg Dealer (Cosmic Fall)"     :  ["Normal", "Expert"],
    "Black Doom (Cosmic Fall)"     :  ["Normal", "Expert"],
    "Diablon (Final Haunt)"        :  ["Normal", "Expert"],
    "Black Doom (Final Haunt)"     :  ["Normal", "Expert"],
    "Devil Doom"                   :  ["Normal"]
}

# Every level and boss
levels_and_bosses = {**levels, **bosses}

# Every story path
routes = {
    "001" :  ["Punishment, Thy Name is Ruin" , 	"DDDDDD"],
    "002" :  ["Prologue to World Conquest"   ,  "DDDDDH"],
    "003" :  ["The March to a Darker World"  ,  "DDDDND"],
    "004" :  ["The Ultimate Ego"             ,  "DDDDNH"],
    "005" :  ["Purification via Ruination"   ,  "DDDHDD"],
    "006" :  ["Apogee of Darkness"           ,  "DDDHDH"],
    "007" :  ["True Soldier of Destruction"  ,  "DDDHND"],
    "008" :  ["Believe in Yourself"          ,  "DDDHNH"],
    "009" :  ["An Android’s Determination"	 ,  "DDDHHD"],
    "010" :  ["For Machine, By Machine..."	 ,  "DDDHHH"],
    "011" :  ["Revenge at Last"	             ,  "DDNDDD"],
    "012" :  ["Ego’s Awakening"	             ,  "DDNDDH"],
    "013" :  ["Destruction and Scorn"	     ,  "DDNDND"],
    "014" :  ["The Last Remaining Purpose"	 ,  "DDNDNH"],
    "015" :  ["The Nightmare’s Insulation"	 ,  "DDNNDD"],
    "016" :  ["The Nightmare’s Sublimation"	 ,  "DDNNDH"],
    "017" :  ["The Loner’s Choice"	         ,  "DDNNND"],
    "018" :  ["Subjugation in Black"	     ,  "DDNNNH"],
    "019" :  ["Replica’s Depression"	     ,  "DDNNHD"],
    "020" :  ["Machine, Machine"	         ,  "DDNNHH"],
    "021" :  ["Disciple from the Darkness"	 ,  "DDNHDD"],
    "022" :  ["Beloved Clone"	             ,  "DDNHDH"],
    "023" :  ["Revenge Upon the Doctor"	     ,  "DDNHND"],
    "024" :  ["The Ultimate Replica"	     ,  "DDNHNH"],
    "025" :  ["Sanction’s Demise"	         ,  "DDNHHD"],
    "026" :  ["Along With My Home"	         ,  "DDNHHH"],
    "027" :  ["The Cleansing of Darkness"	 ,  "DDHDDD"],
    "028" :  ["Birth of a God"	             ,  "DDHDDH"],
    "029" :  ["The Last Soldier’s Grim Fate" ,  "DDHDND"],
    "030" :  ["Isolation and Solitude"	     ,  "DDHDNH"],
    "031" :  ["Archimedes and the Tortoise"	 ,  "DDHDHD"],
    "032" :  ["Where Is My Happiness?"	     ,  "DDHDHH"],
    "033" :  ["Seduced By Taste of Blood"	 ,  "DDHNDD"],
    "034" :  ["A Machine Made for War"	     ,  "DDHNDH"],
    "035" :  ["Original Definition"	         ,  "DDHNND"],
    "036" :  ["Machine Paradise"	         ,  "DDHNNH"],
    "037" :  ["Last Will and Testament"	     ,  "DDHNHD"],
    "038" :  ["Enveloped in Solitude"	     ,  "DDHNHH"],
    "039" :  ["Parricidal Savior"	         ,  "DDHHDD"],
    "040" :  ["Copy of a Savior"	         ,  "DDHHDH"],
    "041" :  ["Excess of Intellect"	         ,  "DDHHND"],
    "042" :  ["Crystallization of Intellect" ,  "DDHHNH"],
    "043" :  ["The Ultimate Confrontation"	 ,  "DDHHHD"],
    "044" :  ["Miracle of Love"	             ,  "DDHHHH"],
    "045" :  ["The World’s Demise"	         ,  "DHDDDD"],
    "046" :  ["The Ultimate Power"	         ,  "DHDDDH"],
    "047" :  ["Dyed in Lovely Darkness..."	 ,  "DHDDND"],
    "048" :  ["Vainglory or Abandonment?"	 ,  "DHDDNH"],
    "049" :  ["Messenger of Ruination"	     ,  "DHDNDD"],
    "050" :  ["Standing at the Summit"	     ,  "DHDNDH"],
    "051" :  ["Controller from the Capsule"	 ,  "DHDNND"],
    "052" :  ["Beyond One’s Own Power..."	 ,  "DHDNNH"],
    "053" :  ["A Clone’s Determination"	     ,  "DHDNHD"],
    "054" :  ["Machine Utopia"	             ,  "DHDNHH"],
    "055" :  ["A Toast to the Ruler"	     ,  "DHDHDD"],
    "056" :  ["Answer from the Black Comet"	 ,  "DHDHDH"],
    "057" :  ["Transcendentalism"	         ,  "DHDHND"],
    "058" :  ["Imperialism"	                 ,  "DHDHNH"],
    "059" :  ["The Weight of One’s Crimes"	 ,  "DHDHHD"],
    "060" :  ["Imprisoned by the Past..."	 ,  "DHDHHH"],
    "061" :  ["The Ultimate World Conquest"	 ,  "DHNDDD"],
    "062" :  ["Black Angel"	                 ,  "DHNDDH"],
    "063" :  ["Under Darkness’ Control"	     ,  "DHNDND"],
    "064" :  ["To Love Oneself"	             ,  "DHNDNH"],
    "065" :  ["Revenge and Determination"	 ,  "DHNDHD"],
    "066" :  ["Birth of the Robot Emperor"	 ,  "DHNDHH"],
    "067" :  ["Shadow, the Black Android"	 ,  "DHNNDD"],
    "068" :  ["A Solitary Android"	         ,  "DHNNDH"],
    "069" :  ["Over the Original"	         ,  "DHNNND"],
    "070" :  ["Machine Sunshine"	         ,  "DHNNNH"],
    "071" :  ["Life is Guilty"	             ,  "DHNNHD"],
    "072" :  ["Fallen Angel of Despair"	     ,  "DHNNHH"],
    "073" :  ["An Eternal Rival..."	         ,  "DHNHDD"],
    "074" :  ["This is Just the Beginning"	 ,  "DHNHDH"],
    "075" :  ["Crystal of Tragic Knowledge"	 ,  "DHNHND"],
    "076" :  ["Shadow’s Second Death...?"	 ,  "DHNHNH"],
    "077" :  ["The Legend of Shadow"	     ,  "DHNHHD"],
    "078" :  ["Power of Love"	             ,  "DHNHHH"],
    "079" :  ["Deep Black"	                 ,  "DHHDDD"],
    "080" :  ["Walk My Way"	                 ,  "DHHDDH"],
    "081" :  ["This is Shadow’s Way of Life" ,  "DHHDND"],
    "082" :  ["A Monarch’s Style"	         ,  "DHHDNH"],
    "083" :  ["In the Gap of Sadness"	     ,  "DHHDHD"],
    "084" :  ["To Be Ignorant of the Past"	 ,  "DHHDHH"],
    "085" :  ["At Vengeance’s End"	         ,  "DHHNDD"],
    "086" :  ["Machine Boys"	             ,  "DHHNDH"],
    "087" :  ["Reborn Along with Sorrow"	 ,  "DHHNND"],
    "088" :  ["With a Fate of Self-Denial"	 ,  "DHHNNH"],
    "089" :  ["I Am Shadow"	                 ,  "DHHNHD"],
    "090" :  ["Shining Within Memory..."	 ,  "DHHNHH"],
    "091" :  ["The Rise and Fall of The ARK" ,  "DHHHND"],
    "092" :  ["Requiem for a Fallen Angel"	 ,  "DHHHNH"],
    "093" :  ["Ultimate Shadow"	             ,  "DHHHHD"],
    "094" :  ["For Love’s Sake"	             ,  "DHHHHH"],
    "095" :  ["A Heart Awoken from Darkness" ,  "NDDDDD"],
    "096" :  ["Destruction From Perfection"	 ,  "NDDDDH"],
    "097" :  ["Darkness’ Strongest Soldier"	 ,  "NDDDND"],
    "098" :  ["Severed Chains"	             ,  "NDDDNH"],
    "099" :  ["Retribution Against Humanity" ,  "NDDHDD"],
    "100" :  ["To Be Known as ‘Ultimate’"	 ,  "NDDHDH"],
    "101" :  ["Dark Warrior’s Advent"	     ,  "NDDHND"],
    "102" :  ["Arriving at the Ego"	         ,  "NDDHNH"],
    "103" :  ["Determination of a Fake"	     ,  "NDDHHD"],
    "104" :  ["Path to the Machine Empire"	 ,  "NDDHHH"],
    "105" :  ["Demise Wrought by Tragedy"	 ,  "NDNDDD"],
    "106" :  ["Turning Sorrow Into Strength" ,  "NDNDDH"],
    "107" :  ["The Liberated Soldier"	     ,  "NDNDND"],
    "108" :  ["Stupefaction’s End"	         ,  "NDNDNH"],
    "109" :  ["Humanity’s Folly"	         ,  "NDNNDD"],
    "110" :  ["Surpassing All Else"	         ,  "NDNNDH"],
    "111" :  ["Soldier of Grief"	         ,  "NDNNND"],
    "112" :  ["Reclaimed Heart"	             ,  "NDNNNH"],
    "113" :  ["Fighting Spirit of Steel"	 ,  "NDNNHD"],
    "114" :  ["Machine Soldier Uprising"	 ,  "NDNNHH"],
    "115" :  ["The Devil Born From Betrayal" ,  "NDNHDD"],
    "116" :  ["Beyond the Truth of Impact"	 ,  "NDNHDH"],
    "117" :  ["The Immortal Android"	     ,  "NDNHND"],
    "118" :  ["The New, Coldhearted Empire"	 ,  "NDNHNH"],
    "119" :  ["A Singular Atonement"	     ,  "NDNHHD"],
    "120" :  ["Spawn of the Devil"	         ,  "NDNHHH"],
    "121" :  ["Black Doom’s Scheme"	         ,  "NDHDDD"],
    "122" :  ["Subjugating Heaven and Earth" ,  "NDHDDH"],
    "123" :  ["Road of the Dark Soldier"	 ,  "NDHDND"],
    "124" :  ["Dark Finale"	                 ,  "NDHDNH"],
    "125" :  ["Realization While On Board"	 ,  "NDHDHD"],
    "126" :  ["Birth of a Champion"	         ,  "NDHDHH"],
    "127" :  ["With the Black Arms"	         ,  "NDHNDD"],
    "128" :  ["The Road to Self-Assurance"	 ,  "NDHNDH"],
    "129" :  ["The Pursuit of Dr. Eggman"	 ,  "NDHNND"],
    "130" :  ["Surpassing His Creator"	     ,  "NDHNNH"],
    "131" :  ["ARK, Colony of Pathos"	     ,  "NDHNHD"],
    "132" :  ["Perfection Lost to Darkness"	 ,  "NDHNHH"],
    "133" :  ["A New Challenge"	             ,  "NDHHDD"],
    "134" :  ["The Machines’ Coup d’Etat"	 ,  "NDHHDH"],
    "135" :  ["A Vow for the Victims"	     ,  "NDHHND"],
    "136" :  ["The Truth of Sadness"	     ,  "NDHHNH"],
    "137" :  ["The Destined Sonic Showdown"	 ,  "NDHHHD"],
    "138" :  ["The Black Hero’s Rebirth"	 ,  "NDHHHH"],
    "139" :  ["Truth, Thy Name is Vengeance" ,  "NNDDDD"],
    "140" :  ["Searching for 'Ultimate'"	 ,  "NNDDDH"],
    "141" :  ["Reborn Hatred for Humanity"	 ,  "NNDDND"],
    "142" :  ["A Future Taken from the Past" ,  "NNDDNH"],
    "143" :  ["The Devils' Victory Song"	 ,  "NNDNDD"],
    "144" :  ["One to Succeed a God"	     ,  "NNDNDH"],
    "145" :  ["Disappointed in Humanity"	 ,  "NNDNND"],
    "146" :  ["Faith Taken from Solitude"	 ,  "NNDNNH"],
    "147" :  ["Planted Memories"	         ,  "NNDNHD"],
    "148" :  ["To Unite Humanity"	         ,  "NNDNHH"],
    "149" :  ["Isolated Soldier Shadow"	     ,  "NNDHDD"],
    "150" :  ["Answer Derived from Truth"	 ,  "NNDHDH"],
    "151" :  ["A Fake’s Disposition"	     ,  "NNDHND"],
    "152" :  ["A New World Without Betrayal" ,  "NNDHNH"],
    "153" :  ["Together With Maria..."	     ,  "NNDHHD"],
    "154" :  ["The Tragedy’s Conclusion"	 ,  "NNDHHH"],
    "155" :  ["The Day That Hope Died"	     ,  "NNNDDD"],
    "156" :  ["Dark Destroyer"	             ,  "NNNDDH"],
    "157" :  ["Diabolical Power"	         ,  "NNNDND"],
    "158" :  ["For Freedom"                  ,  "NNNDNH"],
    "159" :  ["At Least, Be Like Shadow..."	 ,  "NNNDHD"],
    "160" :  ["Seeking a Silent Paradise"	 ,  "NNNDHH"],
    "161" :  ["The Lion’s Awakening"	     ,  "NNNNDD"],
    "162" :  ["Identity"	                 ,  "NNNNDH"],
    "163" :  ["An Android’s Rebellion"	     ,  "NNNNND"],
    "164" :  ["A New Empire’s Beginning"	 ,  "NNNNNH"],
    "165" :  ["Bullets from Tears"	         ,  "NNNNHD"],
    "166" :  ["Journey to Nihility"	         ,  "NNNNHH"],
    "167" :  ["Shadow Surpassing Shadow"	 ,  "NNNHDD"],
    "168" :  ["Dr. Eggman’s Miscalculation"	 ,  "NNNHDH"],
    "169" :  ["Along With the ARK"	         ,  "NNNHND"],
    "170" :  ["Requiem for the Heavens"	     ,  "NNNHNH"],
    "171" :  ["Sonic Dethroned!"	         ,  "NNNHHD"],
    "172" :  ["Justice Reborn in Space"	     ,  "NNNHHH"],
    "173" :  ["Steel Ruler"	                 ,  "NNHDDD"],
    "174" :  ["For the Sake of the Self"	 ,  "NNHDDH"],
    "175" :  ["Farewell to the Past"	     ,  "NNHDND"],
    "176" :  ["Steel Paradise"	             ,  "NNHDNH"],
    "177" :  ["The Guardian With No Past"	 ,  "NNHDHD"],
    "178" :  ["The Ultimate Atonement"	     ,  "NNHDHH"],
    "179" :  ["A Fake’s Aspiration"	         ,  "NNHNDD"],
    "180" :  ["Machine World"	             ,  "NNHNDH"],
    "181" :  ["Twilight Ark"	             ,  "NNHNND"],
    "182" :  ["Compensation for a Miracle"	 ,  "NNHNNH"],
    "183" :  ["The Strongest Hedgehog"	     ,  "NNHNHD"],
    "184" :  ["The Ultimate Punisher"	     ,  "NNHNHH"],
    "185" :  ["Voyage of Reminiscence"	     ,  "NNHHND"],
    "186" :  ["Wandering’s End"	             ,  "NNHHNH"],
    "187" :  ["The Ultimate Proof"	         ,  "NNHHHD"],
    "188" :  ["Punisher of Love"	         ,  "NNHHHH"],
    "189" :  ["Messenger from the Darkness"	 ,  "NHDDDD"],
    "190" :  ["The New Ruler"	             ,  "NHDDDH"],
    "191" :  ["Dark Soldier"	             ,  "NHDDND"],
    "192" :  ["The Road of Light"	         ,  "NHDDNH"],
    "193" :  ["The Machine-Laden Kingdom"	 ,  "NHDDHD"],
    "194" :  ["New Determination"	         ,  "NHDDHH"],
    "195" :  ["Birth of the Dark Soldier"	 ,  "NHDNDD"],
    "196" :  ["A New Journey"	             ,  "NHDNDH"],
    "197" :  ["The Android’s Opposition"	 ,  "NHDNND"],
    "198" :  ["Founding of the Robot Nation" ,  "NHDNNH"],
    "199" :  ["The Eternal Protector"	     ,  "NHDNHD"],
    "200" :  ["The Sinner’s Repose"	         ,  "NHDNHH"],
    "201" :  ["A Hero’s Resolution"	         ,  "NHDHDD"],
    "202" :  ["The Weapons’ Empire"	         ,  "NHDHDH"],
    "203" :  ["Perpetual Voyage"	         ,  "NHDHND"],
    "204" :  ["A Hero’s Atonement"	         ,  "NHDHNH"],
    "205" :  ["Dark Hegemony"	             ,  "NHDHHD"],
    "206" :  ["And the Dream Continues"	     ,  "NHDHHH"],
    "207" :  ["Fighter for Darkness"	     ,  "NHNDDD"],
    "208" :  ["The Path I Believed In"	     ,  "NHNDDH"],
    "209" :  ["Determination’s Daybreak"	 ,  "NHNDND"],
    "210" :  ["Machine Kingdom at Dawn"	     ,  "NHNDNH"],
    "211" :  ["Sinful Protector"	         ,  "NHNDHD"],
    "212" :  ["At the End of the Journey"	 ,  "NHNDHH"],
    "213" :  ["Surmounting the Nightmare"	 ,  "NHNNDD"],
    "214" :  ["Dawn of the Machines"	     ,  "NHNNDH"],
    "215" :  ["Wandering for Eternity"	     ,  "NHNNND"],
    "216" :  ["At Vagrancy’s End"	         ,  "NHNNNH"],
    "217" :  ["The Summit of Power"	         ,  "NHNNHD"],
    "218" :  ["Under the Name of Love"	     ,  "NHNNHH"],
    "219" :  ["Eternally Drifting"	         ,  "NHNHND"],
    "220" :  ["The Importance of Truth"	     ,  "NHNHNH"],
    "221" :  ["The Beginning of Judgment"	 ,  "NHNHHD"],
    "222" :  ["This World’s Guardian"	     ,  "NHNHHH"],
    "223" :  ["Light Born from Darkness"	 ,  "NHHDDD"],
    "224" :  ["The Order of Steel"	         ,  "NHHDDH"],
    "225" :  ["Solitary Journey"	         ,  "NHHDND"],
    "226" :  ["The Fall Home"                ,  "NHHDNH"],
    "227" :  ["Sovereign of All Creation" 	 ,  "NHHDHD"],
    "228" :  ["I Shall Be the One to Judge"  ,  "NHHDHH"],
    "229" :  ["Gone With the Darkness"	     ,  "NHHHND"],
    "230" :  ["The Ultimate Choice"	         ,  "NHHHNH"],
    "231" :  ["I Am the Strongest!"          ,  "NHHHHD"],
    "232" :  ["Justice’s Awakening"	         ,  "NHHHHH"],
    "233" :  ["Prelude to Ruination"	     ,  "HDDDDD"],
    "234" :  ["A World United by Darkness"	 ,  "HDDDDH"],
    "235" :  ["The Pulse of Darkness"	     ,  "HDDDND"],
    "236" :  ["To Just Be Myself"	         ,  "HDDDNH"],
    "237" :  ["Punishment in Jet Black"	     ,  "HDDNDD"],
    "238" :  ["The Ruler’s First Cry"	     ,  "HDDNDH"],
    "239" :  ["Darkness’ Conspiracy"	     ,  "HDDNND"],
    "240" :  ["The Faint Light of Tomorrow"	 ,  "HDDNNH"],
    "241" :  ["Time of Departure"	         ,  "HDDNHD"],
    "242" :  ["Rise of the Machine Kingdom"	 ,  "HDDNHH"],
    "243" :  ["Despair’s Quickening"	     ,  "HDDHDD"],
    "244" :  ["The Beginning"	             ,  "HDDHDH"],
    "245" :  ["Setting Out in the Morning"	 ,  "HDDHND"],
    "246" :  ["The Weapons’ Dawn"	         ,  "HDDHNH"],
    "247" :  ["Pure Ark"	                 ,  "HDDHHD"],
    "248" :  ["Making Up For It in the End"	 ,  "HDDHHH"],
    "249" :  ["The Coming of the Dark Time"	 ,  "HDNDDD"],
    "250" :  ["The Throne of God"	         ,  "HDNDDH"],
    "251" :  ["God of War"	                 ,  "HDNDND"],
    "252" :  ["Howl of Solitude"	         ,  "HDNDNH"],
    "253" :  ["Proof of Existence"	         ,  "HDNDHD"],
    "254" :  ["Ardent Vow"	                 ,  "HDNDHH"],
    "255" :  ["A Deal With the Devil"	     ,  "HDNNDD"],
    "256" :  ["A Reason to Live"	         ,  "HDNNDH"],
    "257" :  ["Induplicable Thoughts"	     ,  "HDNNND"],
    "258" :  ["Steel Struck With Flame"	     ,  "HDNNNH"],
    "259" :  ["A Heart Bound to the ARK"     ,  "HDNNHD"],
    "260" :  ["Tears Shed by the Stars"	     ,  "HDNNHH"],
    "261" :  ["Imitation Complex"	         ,  "HDNHDD"],
    "262" :  ["Steel Combat Boots"	         ,  "HDNHDH"],
    "263" :  ["Protector of the Ashen Moon"	 ,  "HDNHND"],
    "264" :  ["A Demon Drifting"	         ,  "HDNHNH"],
    "265" :  ["The Ultimate Pride"	         ,  "HDNHHD"],
    "266" :  ["I Know the Will of Heaven"	 ,  "HDNHHH"],
    "267" :  ["Ego Dyed in Black"	         ,  "HDHDDD"],
    "268" :  ["Isolation By Choice"	         ,  "HDHDDH"],
    "269" :  ["Faith Without Falsehood"	     ,  "HDHDND"],
    "270" :  ["Machine Empire"	             ,  "HDHDNH"],
    "271" :  ["The Eternally-Closed Door"	 ,  "HDHDHD"],
    "272" :  ["The Sealed-Away Ark of Sin"	 ,  "HDHDHH"],
    "273" :  ["Silver Emergence"	         ,  "HDHNDD"],
    "274" :  ["Pulsating Supercurrent"	     ,  "HDHNDH"],
    "275" :  ["The Reason I Was Born"	     ,  "HDHNND"],
    "276" :  ["The Dark Part of the Galaxy"	 ,  "HDHNNH"],
    "277" :  ["The View From Atop the World" ,  "HDHNHD"],
    "278" :  ["Maria’s Testament"	         ,  "HDHNHH"],
    "279" :  ["A Genius Scientist’s Lineage" ,  "HDHHND"],
    "280" :  ["Distorted Truth"	             ,  "HDHHNH"],
    "281" :  ["A Counterfeit Existence"	     ,  "HDHHHD"],
    "282" :  ["Beloved Memories"	         ,  "HDHHHH"],
    "283" :  ["Birth of a Devil"	         ,  "HHDDDD"],
    "284" :  ["A Dark Myth’s Beginnings"	 ,  "HHDDDH"],
    "285" :  ["Black Thunder"	             ,  "HHDDND"],
    "286" :  ["The Torn-Away Necklace"	     ,  "HHDDNH"],
    "287" :  ["A Soul Sheltered by Iron"	 ,  "HHDDHD"],
    "288" :  ["Steel Nation’s Decree"	     ,  "HHDDHH"],
    "289" :  ["Coronation of Darkness"	     ,  "HHDNDD"],
    "290" :  ["Opened Eyes"	                 ,  "HHDNDH"],
    "291" :  ["The Doctor’s Lie"	         ,  "HHDNND"],
    "292" :  ["The Uninvited Successor"	     ,  "HHDNNH"],
    "293" :  ["The Closed Pandora’s Box"	 ,  "HHDNHD"],
    "294" :  ["A Heart Bound by Sin"	     ,  "HHDNHH"],
    "295" :  ["Courage from Turning Gears"	 ,  "HHDHDD"],
    "296" :  ["Fullmetal Prince"	         ,  "HHDHDH"],
    "297" :  ["Time’s Watchman"	             ,  "HHDHND"],
    "298" :  ["Galaxy’s Requiem"	         ,  "HHDHNH"],
    "299" :  ["Charm of the Chaos Emeralds"	 ,  "HHDHHD"],
    "300" :  ["Promise of a Far-Off Day"	 ,  "HHDHHH"],
    "301" :  ["The Grim Reaper’s Horn"	     ,  "HHNDDD"],
    "302" :  ["A Flame Extinguished by Fate" ,  "HHNDDH"],
    "303" :  ["Shouting at the Morning Sun"	 ,  "HHNDND"],
    "304" :  ["Iron Ambition"	             ,  "HHNDNH"],
    "305" :  ["Sleeping on Hallowed Ground"	 ,  "HHNDHD"],
    "306" :  ["Explanation of the Truth"	 ,  "HHNDHH"],
    "307" :  ["An Android’s Dream"	         ,  "HHNNDD"],
    "308" :  ["Metallic Quickening"	         ,  "HHNNDH"],
    "309" :  ["Funeral Procession in Space"	 ,  "HHNNND"],
    "310" :  ["Lost to the Universe’s Abyss" ,  "HHNNNH"],
    "311" :  ["Destiny for Two"	             ,  "HHNNHD"],
    "312" :  ["The Spun Threads of Fate"	 ,  "HHNNHH"],
    "313" :  ["Ark of the Heavens"	         ,  "HHNHND"],
    "314" :  ["Ghost of The ARK"	         ,  "HHNHNH"],
    "315" :  ["A Pair of Shooting Stars"	 ,  "HHNHHD"],
    "316" :  ["The One Who Maria Entrusted"	 ,  "HHNHHH"],
    "317" :  ["A.I.’s Enlightenment"	     ,  "HHHDDD"],
    "318" :  ["A Dying Empire’s Cry"	     ,  "HHHDDH"],
    "319" :  ["Moon of Atonement"	         ,  "HHHDND"],
    "320" :  ["Tear-Soaked Hometown"	     ,  "HHHDNH"],
    "321" :  ["Sparks on the Horizon"	     ,  "HHHDHD"],
    "322" :  ["A Use for a Saved Life"	     ,  "HHHDHH"],
    "323" :  ["Coffin of Memories"	         ,  "HHHHND"],
    "324" :  ["The Self-Imposed Seal"	     ,  "HHHHNH"],
    "325" :  ["Pretense in the Mirror"	     ,  "HHHHHD"],
    "326" :  ["A Missive from 50 Years Ago"	 ,  "HHHHHH"]
}

# Exclude impossible missions, boss and routes for Gun Android and Cannon Android
exclude_levels = copy.deepcopy(levels)
exclude_levels["Cryptic Castle"].remove("Dark")
exclude_levels["Central City"].remove("Hero")

exclude_boss = copy.deepcopy(bosses)
del exclude_boss["Devil Doom"]

exclude_levels_and_boss = {**exclude_levels, **exclude_boss}

#List of routes to exclude (001–010, 095–104)
exclude_numbers = list(range(1, 11)) + list(range(95, 105))

#Convert to zero-padded strings like '001', '095'
exclude_paths = [f"{num:03}" for num in exclude_numbers]

#Filter routes
exclude_routes = {key: value for key, value in routes.items() if key not in exclude_paths}